.TH yCALC_math 3 2018-apr "linux" "interfacing applications with library"

.SH NAME
yCALC \- fast, powerful, flexible, shared calculation engine

.SH SUMMARY
yCALC is a clean, reliable, debuggable, and shared library for creating
and executing fast, flexible byte-code calculations that can be used in any
programming context (spreadsheet to system utility).




.SH DOCUMENTATION FILES
.nf
yCALC (3)          interfacing applications with library
.B yCALC_math (3)·····specifics of mathmatic functions
yCALC (7)          decision rationale, scope, and objectives
